name: glinet-imagebuild-test

on: workflow_dispatch

env:
  CUSTOM: rtty-openssl=https://api.github.com/repos/innet8/rtty/releases
  PACKAGES: coreutils-base64 bash oping kmod-ipt-iprange iptables-mod-iprange rtty-openssl -gl-cloud-ui speedtest-cpp -gl-ui nginx-ssl nginx-mod-luci hiui-rpc-core hiui-ui-core hiui-app-home hiui-app-clients hiui-app-layout hiui-app-login hiui-app-sdwan hiui-app-settings hiui-app-relayd hiui-app-upgrade hiui-app-wireless hiui-app-network

jobs:
  build:
    name: Build ${{ matrix.mode }} image
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        mode: [ar750s]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/glinet-imagebuilder-action@master
        env:
          MODEL: ${{ matrix.mode }}
          PACKAGES: ${{env.PACKAGES}}
          CUSTOM: ${{env.CUSTOM}}

      - name: Save Build Result
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: |
            *.bin
            *.img
            *.tar
