name: glinet-imagebuild-test

on: workflow_dispatch

env:
  VERSION: 3.216
  PACKAGES: coreutils-base64 bash oping kmod-ipt-iprange iptables-mod-iprange openssh-sftp-server rtty-openssl -gl-cloud-ui -lighttpd -lighttpd-mod-fastcgi -lighttpd-mod-access -lighttpd-mod-cgi -lighttpd-mod-expire -lighttpd-mod-proxy -lighttpd-mod-redirect speedtest-cpp -gl-ui nginx-ssl nginx-mod-luci hiui-rpc-core hiui-ui-core hiui-app-clients hiui-app-layout hiui-app-login hiui-app-sdwan hiui-app-settings hiui-app-relayd hiui-app-upgrade hiui-app-wireless hiui-app-network default-settings

jobs:
  build:
    name: Build ${{ matrix.mode }} image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [b1300]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/glinet-imagebuilder-action@master
        env:
          MODEL: ${{ matrix.mode }}
          PACKAGES: ${{env.PACKAGES}}
          VERSION: ${{env.VERSION}}

      - name: Save Build Result
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: |
            *.bin
            *.img
            *.tar
