name: glinet-imagebuild-test
on: workflow_dispatch

jobs:
  build:
    name: Build ${{ matrix.mode }} image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [usb150,ar750s,mt300n-v2,b1300,ax1800]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/glinet-imagebuilder-action@master
        env:
          MODE: ${{ matrix.mode }}
          PKG: rtty

      - name: Save Build Result
        uses: actions/upload-artifact@v2
        with:
          name: ipk
          path: |
            rtty*.ipk
