name: glinet-imagebuild-release
on:
  push:
    tags:
      - "*"
env:
  CUSTOM: rtty-openssl=https://api.github.com/repos/innet8/rtty/releases
  PACKAGES: coreutils-base64 bash oping luasocket kmod-ipt-iprange iptables-mod-iprange lua-cjson rtty-openssl -gl-cloud-ui -gl-ui -fcgi -lighttpd-mod-fastcgi

jobs:
  build:
    name: Build ${{ matrix.mode }} image
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        mode: [usb150,ar750s,mt300n-v2,b1300,ax1800]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/glinet-imagebuilder-action@master
        env:
          MODEL: ${{ matrix.mode }}
          PACKAGES: ${{env.PACKAGES}}
          CUSTOM: ${{env.CUSTOM}}
          
      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.bin
            *.img
            *.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
