name: test
on: workflow_dispatch
env:
  CUSTOM: rtty-openssl=https://api.github.com/repos/innet8/rtty/releases
  PACKAGES: coreutils-base64 bash oping luasocket kmod-ipt-iprange iptables-mod-iprange lua-cjson -gl-cloud-ui

jobs:
  build:
    name: Build ${{ matrix.mode }} image
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        mode: [b1300]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/glinet-imagebuilder-action@master
        env:
          MODEL: ${{ matrix.mode }}
          PACKAGES: ${{env.PACKAGES}}
          CUSTOM: ${{env.CUSTOM}}
          
      - name: Save Build Result
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: |
            *.bin
            *.img
            *.tar
