name: test
on: workflow_dispatch
env:
  CUSTOM: rtty-openssl=https://api.github.com/repos/innet8/rtty/releases,speedtest-cpp=https://api.github.com/repos/zzzzzhy/speedtest-cpp/releases,nginx-ssl=https://api.github.com/repos/zzzzzhy/hiui/releases,nginx-ssl-util=https://api.github.com/repos/zzzzzhy/hiui/releases
  PACKAGES: coreutils-base64 bash oping luasocket kmod-ipt-iprange iptables-mod-iprange lua-cjson -gl-cloud-ui speedtest-cpp -gl-ui -fcgi -lighttpd-mod-fastcgi nginx-ssl nginx-mod-luci


jobs:
  build:
    name: Build ${{ matrix.mode }} image
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        mode: [b1300,ar750s]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/glinet-imagebuilder-action@master
        env:
          MODEL: ${{ matrix.mode }}
          PACKAGES: ${{env.PACKAGES}}
          CUSTOM: ${{env.CUSTOM}}
          
      - name: Save Build Result
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: |
            *.bin
            *.img
            *.tar
